










#version: '3'
#
#services:
#  database:
#    container_name: mariadb
#    image:  mariadb:10
#    restart: unless-stopped
#    volumes:
#      - ~/docker/mariadb/etc/mysql/conf.d:/etc/mysql/conf.d:ro
#      - ~/docker/mariadb/var/lib/mysql:/var/lib/mysql
#      - ~/docker/mariadb/var/log/maria:/var/log/maria
#    environment:
#      MYSQL_DATABASE: midubang
#      MARIADB_ROOT_HOST: '%'
#      MARIADB_ROOT_PASSWORD: root24
#    command: ['--character-set-server=utf8mb4', '--collation-server=utf8mb4_unicode_ci']
#    ports:
#      - "3306:3306"
#    networks:
#      - test_network
#
#  web:
#    build:
#      context: .
#      dockerfile: Dockerfile
#    ports:
#      - "8080:8080"
#    depends_on:
#      - database
#    networks:
#      - test_network