spring:
    datasource:
        driver-class-name: org.mariadb.jdbc.Driver
        username: root
        url: jdbc:mariadb://localhost:3307/midubang?useSSL=false&characterEncoding=UTF-8&serverTimezone=UTC&allowPublicKeyRetrieval=true
        password: root24
    jpa:
        database-platform: org.hibernate.dialect.MariaDB103Dialect
        hibernate:
            ddl-auto: create-drop
        format_sql: 'true'
        how-sql: 'true'


    redis:
        host: localhost
        port: 6379

    security:
        oauth2:
            client:
                registration:
                    kakao:
                        client-id: 0f6448ff8ab726d19810692f223972fb
                        redirect-uri: http://localhost:8080/api/member/login/oauth2/code/kakao
                        client-authentication-method: POST
                        client-secret: RnxqyU7kxt21xIpY13fU7UJbZ9onoQdR
                        authorization-grant-type: authorization_code
                        scope:
                            - account_email
                        client_name: kakao
                provider:
                    kakao:
                        authorization-uri: https://kauth.kakao.com/oauth/authorize
                        token-uri: https://kauth.kakao.com/oauth/token
                        user-info-uri: https://kapi.kakao.com/v2/user/me
                        user-name-attribute: id

---
spring:
    profiles:
        include: oauth
jwt:
    secret: allihearisraindropsfallingontherooftopohbabytellmewhyyoudhavetogocausethispainifeelitwontgoawaysdmidubang20232022202028




